"""
Run_All_Pipeline.py

INPUT FILES:
- None directly (executes other scripts)

OUTPUT FILES:
- Console output of all executed scripts
- T2_processing.log (generated by individual scripts)

DESCRIPTION:
- Executes the T2 Factor Timing pipeline scripts in sequential order.
- Ensures each script completes successfully before starting the next.
- Streams output to the console so the user can watch progress.
- Version: 1.0
- Date: 2025-11-22
"""

import subprocess
import sys
import os
from datetime import datetime

def run_script(script_name):
    """
    Executes a python script and streams its output to the console.
    Raises an exception if the script fails.
    """
    print(f"\n{'='*80}")
    print(f"Starting {script_name} at {datetime.now().strftime('%H:%M:%S')}")
    print(f"{'='*80}\n")
    
    if not os.path.exists(script_name):
        print(f"ERROR: Script {script_name} not found!")
        sys.exit(1)
        
    # Flush stdout to ensure order of printing
    sys.stdout.flush()
    
    try:
        # Run the script, streaming output to stdout/stderr
        # check=True will raise CalledProcessError if return code != 0
        subprocess.run([sys.executable, script_name], check=True)
        
        print(f"\n{'-'*80}")
        print(f"Finished {script_name} successfully at {datetime.now().strftime('%H:%M:%S')}")
        print(f"{'-'*80}\n")
        
    except subprocess.CalledProcessError as e:
        print(f"\n{'!'*80}")
        print(f"ERROR: {script_name} failed with exit code {e.returncode}")
        print(f"{'!'*80}\n")
        sys.exit(e.returncode)
    except KeyboardInterrupt:
        print("\nExecution interrupted by user.")
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred while running {script_name}: {e}")
        sys.exit(1)

def main():
    # Define the sequence of scripts to run
    scripts = [
        "Step Zero Create P2P Scores.py",
        "Step One Create T2Master.py",
        "Step Two Create Normalized Tidy.py",
        "Step Two Point Five Create Benchmark Rets.py",
        "Step Three Top20 Portfolios Fast.py",
        "Step Four Create Monthly Top20 Returns FAST.py",
        "Step Five FAST.py",
        "Step Six Create Country alphas from Factor alphas.py",
        "Step Seven Visualize Factor Weights.py",
        "Step Eight Write Country Weights.py",
        "Step Eight Point Five Write Country Weights US Adjustment.py",
        "Step Nine Calculate Portfolio Returns.py",
        "Step Ten Create Final Report.py",
        "Step Fourteen Target Optimization.py",
        "Step Fifteen Market Regime Analysis.py",
        "Step Sixteen Market Regime Analysis.py",
        "Step Seventeen Market Regime Analysis.py",
        "Step Eighteen Asset Class Charts.py",
        "Step Twenty PORCH.py",
        "Step Twenty One Master Report.py",
        "Step FINALFINAL.py"
    ]
    
    print(f"Starting T2 Factor Timing Pipeline Execution")
    print(f"Total steps: {len(scripts)}")
    start_time = datetime.now()
    
    for i, script in enumerate(scripts, 1):
        print(f"Step {i}/{len(scripts)}: {script}")
        run_script(script)
        
    duration = datetime.now() - start_time
    print(f"\n{'='*80}")
    print(f"Pipeline execution completed successfully!")
    print(f"Total duration: {duration}")
    print(f"{'='*80}")

if __name__ == "__main__":
    main()

